#!/bin/bash

dir=$(dirname "${BASH_SOURCE[0]}")
if [ "$dir" = "." ]
then
    cd ..
fi

VADER_PATH=vader.vim

if ! [ -d $VADER_PATH ]
then
    # local testing
    VADER_PATH=~/.vim/bundle/vader.vim
fi

vim -esNu <(cat << VIMRC
set rtp+=$VADER_PATH
set rtp+=.
VIMRC) -c 'Vader! test/**' > /dev/null
